<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_drop_icon_logout</name>
   <tag></tag>
   <elementGuidId>9f9b205b-9b44-4997-9d65-3613d339c191</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//b[@class='caret']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//b[@class='caret']</value>
   </webElementProperties>
</WebElementEntity>
